### ISSUE TITLE
v1 Migration error with useData

### ISSUE THREAD

**Issue by arthurgailes** [vikejs/vike-react#116]
Hello,

I got the following error while trying to migrate to the v1 design. 

Edit: I get the error at the bottom while trying to add useData()/+data for the first time. It occurs even if +data doesn't exist, or if it just returns an empty object.

```
9:03:08 AM [vike][request(11)] Following error was thrown by the onRenderHtml() hook defined at /renderer/+onRenderHtml.tsx
Error: You stumbled upon a vike-react bug. Go to https://github.com/vikejs/vike-react/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at assert (file:///mypath/node_modules/.pnpm/vike-react@0.4.10_react-dom@18.2.0_react@18.2.0_vike@0.4.171_vite@4.4.9/node_modules/vike-react/dist/utils/assert.js:4:11)
    at usePageContext (file:///mypath/node_modules/.pnpm/vike-react@0.4.10_react-dom@18.2.0_react@18.2.0_vike@0.4.171_vite@4.4.9/node_modules/vike-react/dist/hooks/usePageContext.js:21:5)
    at Proxy.useData (file:///mypath/node_modules/.pnpm/vike-react@0.4.10_react-dom@18.2.0_react@18.2.0_vike@0.4.171_vite@4.4.9/node_modules/vike-react/dist/hooks/useData.js:4:22)
    at Page (mypath\apps\heat\vite\pages\toolkit\+Page.tsx:7:16)
    at renderWithHooks (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:5724:16)    
    at renderIndeterminateComponent (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:5797:15)
    at renderElement (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6012:7)       
    at renderNodeDestructiveImpl (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderNode (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6325:12)
    at renderChildrenArray (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6277:7) 
    at renderNodeDestructiveImpl (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6207:7)
    at renderNodeDestructive (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderNode (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6325:12)
    at renderHostElement (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:5708:3)   
    at renderElement (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6018:5)       
    at renderNodeDestructiveImpl (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderIndeterminateComponent (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:5851:7)
    at renderElement (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6012:7)       
    at renderNodeDestructiveImpl (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderIndeterminateComponent (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:5851:7)
    at renderElement (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6012:7)       
    at renderNodeDestructiveImpl (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderContextProvider (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:5986:3)
    at renderElement (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6083:11)      
    at renderNodeDestructiveImpl (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderNode (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6325:12)
    at renderChildrenArray (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6277:7) 
    at renderNodeDestructiveImpl (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6207:7)
    at renderNodeDestructive (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderNode (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6325:12)
    at renderChildrenArray (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6277:7) 
    at renderNodeDestructiveImpl (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6207:7)
    at renderNodeDestructive (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderContextProvider (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:5986:3)
    at renderElement (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6083:11)      
    at renderNodeDestructiveImpl (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderIndeterminateComponent (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:5851:7)
    at renderElement (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6012:7)       
    at renderNodeDestructiveImpl (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderNode (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6325:12)
    at renderChildrenArray (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6277:7) 
    at renderNodeDestructiveImpl (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6207:7)
    at renderNodeDestructive (mypath\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
```

**Comment by brillout** [comment]
See https://github.com/vikejs/vike-react/issues/115. Just released `vike-react@0.4.11` which doesn't include the misleading error message anymore.
