### ISSUE TITLE
Vike react bug

### ISSUE THREAD

**Issue by olgakisel** [vikejs/vike-react#130]
Error: You stumbled upon a vike-react bug. Go to https://github.com/vikejs/vike-react/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at assert (http://localhost:6006/utils/assert.ts:5:9)
    at usePageContext (http://localhost:6006/utils/usePageContext.tsx:44:3)
    at useCreateTransformPath (http://localhost:6006/services/useCreateTransformPath.ts:6:19)
    at useHybridRouter (http://localhost:6006/services/router/useHybridRouter.ts:12:31)
    at FxProfileHeroPanel (http://localhost:6006/components/[Pages]/FundDetailPage/mapping/FxProfileHeroPanel.tsx:39:7)
    at renderWithHooks (http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-B6JH7DXR.js?v=741b7615:11568:26)
    at mountIndeterminateComponent (http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-B6JH7DXR.js?v=741b7615:14946:21)
    at beginWork (http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-B6JH7DXR.js?v=741b7615:15934:22)
    at beginWork$1 (http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-B6JH7DXR.js?v=741b7615:19781:22)
    at performUnitOfWork (http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-B6JH7DXR.js?v=741b7615:19226:20)

**Comment by brillout** [comment]
Update vike-react to it's latest version.

**Comment by brillout** [comment]
But feel free to reach out if you still run into issues.

**Comment by olgakisel** [comment]
Hey, to confirm, I have update vike and vike-react. I still see the same issue. I see this issue while working in storybook.
Error: You stumbled upon a vike-react bug. Go to https://github.com/vikejs/vike-react/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at assert (http://localhost:6006/utils/assert.ts:5:9)
    at usePageContext (http://localhost:6006/utils/usePageContext.tsx:44:3)
    at useCreateTransformPath (http://localhost:6006/services/useCreateTransformPath.ts:6:19)
    at useHybridRouter (http://localhost:6006/services/router/useHybridRouter.ts:12:31)
    at FxProfileHeroPanel (http://localhost:6006/components/[Pages]/FundDetailPage/mapping/FxProfileHeroPanel.tsx:39:7)
    at renderWithHooks (http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-B6JH7DXR.js?v=efd3fa5e:11568:26)
    at mountIndeterminateComponent (http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-B6JH7DXR.js?v=efd3fa5e:14946:21)
    at beginWork (http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-B6JH7DXR.js?v=efd3fa5e:15934:22)
    at beginWork$1 (http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-B6JH7DXR.js?v=efd3fa5e:19781:22)
    at performUnitOfWork (http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-B6JH7DXR.js?v=efd3fa5e:19226:20)

 Here is my list of dependencies in package.json:
   "dependencies": {
    "@chakra-ui/react": "^2.8.2",
    "@datadog/browser-rum": "^5.10.0",
    "@emotion/react": "^11.11.3",
    "@emotion/styled": "^11.11.0",
    "@fontsource-variable/noto-sans": "^5.0.2",
    "@fontsource/noto-sans": "^5.0.18",
    "@hattip/adapter-node": "^0.0.41",
    "@irrelon/cache-express": "^1.0.0",
    "@irrelon/emitter": "^6.1.0",
    "@irrelon/path": "^6.2.5",
    "@irrelon/promise-map": "^2.0.2",
    "@originjs/vite-plugin-commonjs": "^1.0.3",
    "@trpc/client": "^11.0.0-next-beta.283",
    "@trpc/server": "^11.0.0-next-beta.283",
    "@types/compression": "^1.7.5",
    "@types/qs": "^6.9.11",
    "@vitejs/plugin-react": "^4.3.1",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "cross-fetch": "^4.0.0",
    "dayjs": "^1.11.10",
    "dd-trace": "^5.14.1",
    "dotenv": "^16.4.5",
    "express": "^4.18.2",
    "framer-motion": "^11.0.3",
    "highcharts": "^11.3.0",
    "highcharts-react-official": "^3.2.1",
    "html-entities": "^2.4.0",
    "html-react-parser": "^5.1.2",
    "i18next": "^23.8.2",
    "i18next-resources-to-backend": "^1.2.0",
    "node-cache": "^5.1.2",
    "node-fetch-cache": "^4.1.0",
    "qs": "^6.11.2",
    "react": "^18.2.0",
    "react-device-detect": "^2.2.3",
    "react-dom": "^18.2.0",
    "react-i18next": "^14.0.5",
    "react-icons": "^5.0.1",
    "react-streaming": "^0.3.20",
    "rollup-plugin-polyfill-node": "^0.13.0",
    "server-only-context": "^0.1.0",
    "stream-browserify": "^3.0.0",
    "telefunc": "^0.1.70",
    "tsx": "^4.7.0",
    "ultrafetch": "^0.4.0",
    "vike": "^0.4.179",
    "vike-react": "^0.4.17",
    "vite": "5.1.5",
    "zod": "^3.22.4"
  }

**Comment by brillout** [comment]
The [assertion was removed](https://github.com/vikejs/vike-react/commit/2cc16cfa7a5b434031c528604d3c10c758678a31), so you must be using an older version. Make sure to `rm -fr node_modules/.vite`.
